version: "3.5"

services:
  bootnode:
    container_name: snarkos-bootnode
    image: aleohq/snarkos:groth16-devnet
    volumes:
      - snarkos-bootn-vol:/aleo/data
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --port 14131 --rpc-port 13031 --is-bootnode --ip 172.17.17.11 --connect 172.17.17.11:14131"]
    ports:
      - 13031:13031
      - 14131:14131
    networks:
      aleo_devnet:
        ipv4_address: 172.17.17.11

  client:
    container_name: snarkos-client
    image: aleohq/snarkos:groth16-devnet
    volumes:
      - snarkos-client-vol:/aleo/data   
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --port 14132 --rpc-port 13032 --ip 172.17.17.12 --connect 172.17.17.11:14131"]
    ports:
      - 13032:13032
      - 14132:14132
    networks:
      aleo_devnet:
        ipv4_address: 172.17.17.12

  miner:
    container_name: snarkos-miner
    image: aleohq/snarkos:groth16-devnet
    volumes:
      - snarkos-miner-vol:/aleo/data
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --port 14133 --rpc-port 13033 --is-miner --miner-address ${ALEO_ADDRESS} --ip 172.17.17.13 --connect 172.17.17.11:14131"]
    ports:
      - 13033:13033
      - 14133:14133
    networks:
      aleo_devnet:
        ipv4_address: 172.17.17.13

networks:
  aleo_devnet:
    ipam:
      driver: default
      config:
        - subnet: "172.17.17.0/24"

volumes:
  snarkos-bootn-vol:
  snarkos-miner-vol:
  snarkos-client-vol:
