version: "3"

services:
    bootnode:
        container_name: snarkos-bootnode
        image: aleohq/snarkos:groth16-devnet
        volumes:
            - snarkos-bootn-vol:/aleo/data
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --is-bootnode  --verbose 3 --host bootnode:14131 --rpc-port 13031 --connect bootnode:14131"]
        ports:
            - 13031:13031
            - 14131:14131
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M
            restart_policy:
                condition: on-failure
                max_attempts: 3

    client:
        container_name: snarkos-client
        image: aleohq/snarkos:groth16-devnet
        volumes:
            - snarkos-client-vol:/aleo/data
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --host client:14132 --rpc-port 13032 --connect bootnode:14131"]
        ports:
            - 13032:13032
            - 14132:14132
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 512M
                reservations:
                    memory: 256M
            restart_policy:
                condition: on-failure
                max_attempts: 3

    miner:
        container_name: snarkos-miner
        image: aleohq/snarkos:groth16-devnet
        volumes:
            - snarkos-miner-vol:/aleo/data
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ["bash", "-c", "/aleo/bin/snarkos -d /aleo/data --verbose 3 --rpc-port 13033 --is-miner --miner-address ${ALEO_ADDRESS} --host client:14133 --connect bootnode:14131"]
        ports:
            - 13033:13033
            - 14133:14133
        deploy:
            resources:
                limits:
                    cpus: "3.00"
                    memory: 7168M
                reservations:
                    memory: 4096M
            restart_policy:
                condition: on-failure
                max_attempts: 3


volumes:
    snarkos-bootn-vol:
    snarkos-miner-vol:
    snarkos-client-vol:
