[package]
name = "snarkos-rpc-types"
version = "1.3.16"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "RPC for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md", "documentation/" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkos-network]
path = "../network"
version = "1.3.16"

[dependencies.chrono]
version = "0.4"
features = [ "serde" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]
