{
 "title": "snarkOS",
 "tags": [
  "snarkos",
  "aleo"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Aleo Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snarkos_blocks_height_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Seconds/Block over last minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  1 / rate(snarkos_blocks_height_total{}[1m])\n) < +inf",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "snarkos_blocks_height_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Restricted Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "snarkos_router_restricted_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "snarkos_blocks_transactions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(snarkos_blocks_transactions_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max(snarkos_blocks_coinbase_target)",
     "legendFormat": "Coinbase Target"
    },
    {
     "expr": "max(snarkos_blocks_proof_target)",
     "legendFormat": "Proof Target"
    },
    {
     "expr": "max(snarkos_blocks_cumulative_proof_target)",
     "legendFormat": "Cumulative Proof Target"
    }
   ]
  },
  {
   "title": "Total Solutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "snarkos_blocks_solutions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "snarkvm_ledger_committee_total_stake",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SnarkOS BFT Connected Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "snarkos_bft_connected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "snarkos_router_connected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Candidate Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "snarkos_router_candidate_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "BFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Current Round",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_primary_proposal_round",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Committed Round",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_consensus_last_committed_round",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elected Leaders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_leaders_elected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certified Batches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_bft_primary_certified_batches",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed Certificates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snarkos_consensus_committed_certificates_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Certificate Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(snarkos_consensus_certificate_commit_latency_secs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Rounds Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(snarkos_bft_commit_rounds_latency_secs)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unconfirmed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "snarkos_consensus_unconfirmed_transactions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unconfirmed Solutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "snarkos_consensus_unconfirmed_solutions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unconfirmed Transmissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "snarkos_consensus_unconfirmed_transmissions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "avg(snarkos_consensus_block_latency_secs)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "TCP Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 84 },
   "targets": [
    { "expr": "snarkos_tcp_tasks_total", "legendFormat": "__auto" }
   ]
  }
 ]
}