name: Codecov

on:
  push:
    branches: [ testnet2-2022 ]
  pull_request:
    branches: [ '*' ]

jobs:
  check:
    name: snarkos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install libclang-dev

      - name: coverage
        run: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin cargo tarpaulin -t 1800

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error:     true
